version: "3"

services:
  next-app:
    container_name: Portfolio
    build:
      context: ./
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./:/app/
    restart: always
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
